### PR TITLE
fix: fixed warning emitted on PHP 8.0.0 onwards

### PR DESCRIPTION
**Pull request by dennisenderink**

### CODE REVIEW

**Comment by dennisenderink** [comment]
@polevaultweb it would be much appreciated if this pull request were to be merged. :)

**Comment by jmslbam** [comment]
yes please, I came here to open the same PR :)

**Comment by lgobatto** [comment]
same here :-)

**Comment by LucidNinja** [comment]
Please merge this!!

**Comment by dennisenderink** [comment]
Thanks very much @polevaultweb!

**Comment by lgobatto** [comment]
Thank you all guys!

Em qui., 4 de mai. de 2023 às 10:52, Dennis Enderink <
***@***.***> escreveu:

**Pull request merged**
